import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

import MainBanner from "../components/LandingPageComponents/mainbanner"

import Explore from "../components/LandingPageComponents/explore"
import Testimonial from "../components/LandingPageComponents/testimonial"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainBanner />
      <Testimonial />


      <Explore />




    </div>
  )
}

export default Home
