import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Navbar from "./components/Navbar"
import MainBanner from "./components/mainbanner"

import Explore from "./components/explore"
import Footer from './components/footer'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <MainBanner />
    
      
      <Explore />
      <Footer />

     
     
    </div>
  )
}

export default Home
